[package]
name = "strata"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.7"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
pulldown-cmark = "0.10"
time = { version = "0.3", features = ["formatting"] }
